final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from school.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('school/', include('school.urls', namespace='school')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.contrib import admin
from django.urls import path, include
from school.views import index, teachers, about_us, admission, news_one, paid_services, departments, requirements, equipment, scholarship

app_name = 'school'

urlpatterns = [
    path('page/<int:page>', index, name='paginator'),
    path('teachers/', teachers, name='teachers'),
    path('about-us/', about_us, name='about_us'),
    path('admission/', admission, name='admission'),
    path('news/<int:news_id>', news_one, name='news_one'),
    path('paid_services/', paid_services, name='paid_services'),
    path('departments/', departments, name='departments'),
    path('requirements/', requirements, name='requirements'),
    path('equipment/', equipment, name='equipment'),
    path('scholarship/', scholarship, name='scholarship'),
]

school/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    name = models.CharField(max_length=30)
    img = models.ImageField()
    description = models.TextField()

    def __str__(self):
        return self.name

class Questions(models.Model):
    question = models.TextField()
    email = models.EmailField()

class Teachers(models.Model):
    name = models.CharField(max_length=30)
    img = models.ImageField()
    description = models.TextField()

    def __str__(self):
        return self.name

class Licenses(models.Model):
    name = models.CharField(max_length=50)
    file = models.FileField()

class Awards(models.Model):
    name = models.CharField(max_length=50)
    img = models.ImageField()

class Admission(models.Model):
    student_name = models.CharField(max_length=50)
    parent_name = models.CharField(max_length=50)
    class_number = models.CharField(max_length=10)
    student_pd = models.CharField(max_length=50)
    parent_pd = models.CharField(max_length=50)

school/forms.py
from django import forms
from school.models import Questions, Admission


class QuestionsForm(forms.ModelForm):
    question = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Напишите вопрос'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите адрес эл. почты'
    }))

    class Meta:
        model = Questions
        fields = ('question', 'email')

class AdmissionForm(forms.ModelForm):
    student_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Имя ученика'
    }))
    parent_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Имя родителя'
    }))
    class_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Класс'
    }))
    student_pd = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'ПД ученика'
    }))
    parent_pd = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'ПД родителя'
    }))

    class Meta:
        model = Admission
        fields = ('student_name', 'parent_name', 'class_number', 'student_pd', 'parent_pd')

school/views.py
from django.shortcuts import render
from school.models import News, Teachers, Licenses, Awards
from django.core.paginator import Paginator
from school.forms import QuestionsForm, AdmissionForm
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy


def index(request, page=1):
    news = News.objects.all()
    per_page = 3
    paginator = Paginator(news, per_page)
    news_paginator = paginator.page(page)

    if request.method == 'POST':
        form = QuestionsForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = QuestionsForm()

    context = {
        'news': news_paginator,
        'form': form
    }
    return render(request, 'school.html', context)

def teachers(request):
    context = {
        'teachers': Teachers.objects.all()
    }
    return render(request, 'teachers.html', context)

def about_us(request):
    context = {
        'licenses': Licenses.objects.all(),
        'awards': Awards.objects.all()
    }
    return render(request, 'about_us.html', context)

def admission(request):
    if request.method == 'POST':
        form = AdmissionForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('school:admission'))
    else:
        form = AdmissionForm()

    context = {
        'form': form
    }
    return render(request, 'admission.html', context)

def news_one(request, news_id):
    context = {
        'news_one': News.objects.get(id=news_id),
    }
    return render(request, 'news_one.html', context)

def paid_services(request):
    return render(request, 'paid_services.html')

def departments(request):
    return render(request, 'departments.html')

def requirements(request):
    return render(request, 'requirements.html')

def equipment(request):
    return render(request, 'equipment.html')

def scholarship(request):
    return render(request, 'scholarship.html')

school/templates/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div class="container">
        <h1 class="news_header">История школы</h1>
        <p>Год основания школы: 1925</p>

        <p>История средней школы №1 г. Симай начинается в 1922 году.</p>

        <p>В 1924 году в школе была создана пионерская организация. Школа являлась единственным очагом культуры города.</p>

        <p>До 1936 года школа была семилетней.

            В 1936 Школа №1 становится средней.

            В 1939 - 1940 уч. году средняя школа №1 становится базовой школой всего района.
        </p>

        <p>В годы великой отечественной войны учащиеся школ №2 и №3 занимались в первой школе, занятия шли в три смены.

            С первых дней войны учителя стали уходить на фронт. Поредели ряды юношей старших классов. 12 учителей и 65 учащихся школы не вернулись с полей сражений, в их честь установлен памятник во дворе школы.

            В 1963 году было сдано в эксплуатацию новое здание школы, в котором занимаются и в настоящее время. За все годы школа может гордиться своими выпускниками.
        </p>
        <div></div>
        <h2 class="news_header">Контактная информация</h2>

        <div class="contacts">
            <div>
                <p>Контакты руководства:</p>
                <p>+375(29)305-55-78</p>
            </div>
            <div>
                <p>Адрес:</p>
                <p>г.Минск ул.Революционная 8</p>
            </div>
            <img class="contacts_img" src="{% static 'img/map.png' %}" alt="">
        </div>
        <div></div>
        <h2 class="news_header">Лицензии</h2>

        {% for license in licenses %}
        <div class="lisence">
            <p>{{ license.name }}</p>
            <a href="{{ license.file.url }}">Посмотреть</a>
        </div>
        {% endfor %}

        <h2 class="news_header">Награды</h2>
        {% for award in awards %}
        <div>
            <img class="contacts_img" src="{{ award.img.url }}" alt="">
            <p>{{ award.name }}</p>
        </div>
        {% endfor %}


    </div>
{% endblock %}

school/templates/admission.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <h1 class="news_header">Заполните форму на поступление</h1>
        <form action="{% url 'school:admission' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.student_name.id_for_label }}">ФИО ученика</label>
                {{form.student_name}}
            </div>
            <div class="form-group">
                <label for="{{ form.parent_name.id_for_label }}">ФИО родителя</label>
                {{ form.parent_name }}
            </div>
            <div class="form-group">
                <label for="{{ form.class_number.id_for_label }}">Класс</label>
                {{ form.class_number }}
            </div>
            <div class="form-group">
                <label for="{{ form.student_pd.id_for_label }}">ПД ученика</label>
                {{ form.student_pd }}
            </div>
            <div class="form-group">
                <label for="{{ form.parent_pd.id_for_label }}">ПД родителя</label>
                {{ form.parent_pd }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>

    </div>
{% endblock %}

school/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    <header class="header">
        <a class="header-logo" href="/">SCHOOL</a>
        <nav class="header-menu">
            <ul class="header-menu-list">
                <li class="header-menu-item"><a class="header-menu-link" href="{% url 'school:about_us' %}">О нас</a></li>
                <li class="header-menu-item"><a class="header-menu-link" href="{% url 'school:teachers' %}">Преподаватели</a></li>
                <li class="header-menu-item"><a class="header-menu-link" href="{% url 'school:admission' %}">Поступление</a></li>
                <li class="header-menu-item"><a class="header-menu-link" href="{% url 'school:paid_services' %}">Платные услуги</a></li>
              
            </ul>
        </nav>
    </header>

    {% block main %}{% endblock %}

    <footer class="footer">
        <div class="footer_wrapper">
            <div class="footer_container">
                <div class="footer_contacts">
                    <p class="footer_item">Контакты</p>
                    <p>+375(29)305-55-78</p>
                    +375(33)880-95-17
                </div>
                <div class="footer_location">
                    <p class="footer_item">Адрес</p>
                    <p>г.Минск ул.Революционная 8</p>
                    <p>.</p>
                </div>
                <div class="footer_working_hours">
                    <p class="footer_item">Рабочие часы</p>
                    <p>пн-пт 09:00-18:00</p>
                    сб-вс 10:00-16:00
                </div>           
            </div>
            <div>
                <p class="footer_logo">SCHOOL</p>
            </div>
        </div>
    </footer>
    
</body>
</html>

school/templates/departments.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <h1 class="news_header">Структура и органы управления образовательной организацией</h1>
        <p>Управление учреждением осуществляется в соответствии с законодательством Российской Федерации, законодательством Мурманской области, Уставом учреждения и строится на основе сочетания принципов единоначалия и коллегиальности.</p>
        <p>Органами управления учреждения являются наблюдательный совет учреждения, директор учреждения, общее собрание (конференция) работников и учащихся учреждения, общее собрание (конференция) работников учреждения, педагогический совет, совет учреждения, а также могут формироваться другие коллегиальные органы управления.</p>
        <div class="news_div"></div>
        <div class="news_div"></div>
        <div class="news_div"></div>
    </div>
{% endblock %}

school/templates/equipment.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <h1 class="news_header">Материально-техническое обеспечение и оснащенность образовательного процесса</h1>
        <p>Кабинеты школы оснащены необходимыми учебно-дидактическим комплексами. Компьютерные технологии используются в управлении и в преподавании.
Оборудованные учебные кабинеты, объекты для проведения практических занятий, библиотеки, объекты спорта, средства обучения и воспитания, приспособленные для использования инвалидами и лицами с ограниченными возможностями здоровья, отсутствуют.</p>
        <p>Учебно-материальная база школы позволяет организованно, на современном уровне проводить учебно-воспитательную работу с учащимися. Во всех кабинетах установлены персональные компьютеры.</p>
        <div class="news_div"></div>
        <div class="news_div"></div>
        <div class="news_div"></div>
    </div>
{% endblock %}

school/templates/news_one.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <img class="news_img"
                             src="{{ news_one.img.url }}"
                             alt="">
        <p>{{ news_one.description }}</p>
        <div class="news_div"></div>
    <p></p>
    <p></p>
    <p></p>
    <p></p>

    </div>
{% endblock %}

school/templates/paid_services.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <p class="news_header">Социально-личностное направление</p>
        <div class="paid_div">
            <div class="paid_serv">
                <p>Подготовка к обучению в школе</p>
                <p>140 руб.</p>
            </div>
            <div class="paid_serv">
                <p>Английский язык</p>
                <p>100 руб.</p>
            </div>
            <div class="paid_serv">
                <p>Эмоционально-волевое развитие с использованием сенсорной комнаты</p>
                <p>70 руб.</p>
            </div>
            <div class="paid_serv">
                <p>Удивительный мир</p>
                <p>80 руб.</p>
            </div>
        </div>
        <p class="news_header">Художественно-эстетическое направление</p>
        <div class="paid_serv">
            <p>Студия народного танца</p>
            <p>80 руб.</p>
        </div>
        <div class="paid_serv">
            <p>Студия эстрадного танца</p>
            <p>40 руб.</p>
        </div>
        <div class="paid_serv">
            <p>Музыкально-театрализованная деятельность</p>
            <p>40 руб.</p>
        </div>
        <div class="paid_serv">
            <p>Юный художник</p>
            <p>50 руб.</p>
        </div>
    </div>
{% endblock %}

school/templates/requirements.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <h1 class="news_header">Образовательные стандарты и требования</h1>
        <p>Образовательный стандарт призван обеспечить:
оптимальную степень упорядочения структуры, содержания специального образования,
его результатов, объема оптимальной учебной нагрузки для учащихся с ОПФР;
преемственность в содержании специального образова ния;
регулирование взаимоотношений участников образовательного процесса в достижении
целей специального образования, повышении его качества.
</p>
        <p>Образовательный стандарт раскрывает область его применения, содержит опред еления
терминов основных объектов стандартизации, общие положения, а также включает:
цель и задачи специального образования;
общие требования:
к учреждениям, обеспечивающим получение специального образования;
к специальным условиям для получения образования учащимися с ОПФР;
к документам об образовании;
к обязательному минимуму содержания образования на базовом уровне изучения
учебных предметов для учащихся с ОПФР в соответствии с их познавательными
возможностями в адекватной их здоровью среде обучения;
к составу учебных предметов и коррекционных занятий для учреждений,
обеспечивающих получение специального образования;
к объему оптимальной учебной нагрузки в каждом классе в учебную неделю;
к особенностям организации образовательного процесса в учр еждениях,
обеспечивающих получение специального образования;
к уровню подготовки выпускников с ОПФР в соответствии с их познавательными
возможностями.
Общие требования к обязательному минимуму содержания специального образования на
базовом уровне изучения учебных предметов, уровню подготовки выпускников по учебному
предмету устанавливаются образовательными стандартами по соответствующим учебным
предметам.
Общие требования к перечню учебных предметов и коррекционных занятий для
учреждений, обеспечивающих получение специального образования, устанавливаются
настоящим образовательным стандартом в зависимости от структуры и степени тяжести
</p>
        <p>Целью специального образования является повышение качества жизни учащихся с ОПФР
через реализацию их права на получение образования или коррекционно -педагогической
помощи в соответствии с их познавательными возможностями и состоянием здоровья.
Задачи специального образования:
обеспечение специальных условий для овладения учащимися с ОПФР основами наук,
навыками умственного и физического труда, различными видами познавательной, творческой
и коммуникативной деятельности в соответствии с их познавательными возможностями и
состоянием здоровья;
формирование у учащихся с ОПФР готовности к трудовой деятельности,
самостоятельному жизненному выбору и активной адаптации в социуме, созидательному и
ответственному участию в жизнедеятельности семьи, общества и государства;
сохранение и укрепление физического и психического здоровья учащихся, воспитание
бережного и ответственного отношения к собственному здоровью и здоровью других граждан,
формирование гигиенических навыков, опыта здорового образа жизни и безопасного
поведения.</p>
        <p>На уровне общего среднего образования к учреждениям, обеспечивающим получение
специального образования, относятся:
специальные учреждения образования;
общеобразовательные учреждения, создавшие условия для получения образования
учащимися с ОПФР.
В зависимости от физических и (или) психических нарушений развития детей с ОПФР
создаются следующие специальные учреждения образования:
специальная общеобразовательная школа (школа-интернат) для детей с нарушениями
зрения;
специальная общеобразовательная школа (школа-интернат) для детей с нарушениями
функций опорно-двигательного аппарата;
специальная общеобразовательная школа (школа-интернат) для детей с тяжелыми
нарушениями речи;
специальная общеобразовательная школа (школа-интернат) для детей с нарушениями
психического развития (трудностями в обучении);
специальная общеобразовательная школа (школа-интернат) для детей с нарушением
слуха (первое и второе отделения);
вспомогательная школа (школа-интернат) (первое и второе отделения);
центр коррекционно-развивающего обучения и реабилитации.
Ко всем специальным учреждениям образования предъявляются следующие общие
требования.
Специальное учреждение образования является юридическим лицом и осуществляет
свою деятельность в соответствии с Законами Республики Беларусь «Об образовании», «Об
образовании лиц с особенностями психофизического развития (специальном образовании)»,
«Об общем среднем образовании», другим законодательством Республики Беларусь,
настоящим образовательным стандартом специального образования, Положением о
специальной общеобразовательной школе (школе-интернате), Положением о вспомогательной
школе (школе-интернате), Положением о центре коррекционно -развивающего обучения и
реабилитации, уставами названных специальных учреждений образования.
Материально-техническая база специального учреждения образования формируется
учредителем в соответствии с установленными законодательством Республики Беларусь
нормативами.
Помещения, кабинеты, лаборатории, площадки оснащаются средствами обучения,
учебным оборудованием в соответствии с перечнем средств обучения, учебного оборудования
для специальных учреждений образования и общеобразовательных учреждений,
утверждаемым Министерством образования Республики Беларусь.
Специальные учреждения образования комплектуются педагогическими работниками,
имеющими высшее педагогическое (дефектологическое) образование и (или) квалификацию
учителя-дефектолога (учитель-дефектолог, учитель-логопед, сурдопедагог, тифлопедагог,
олигофренопедагог) и (или) базовое образование, соответствующее профилю преподаваемого
учебного предмета, и необходимую квалификацию.
Финансирование расходов на содержание специального учреждения образования
осуществляется в соответствии с государственными нормативами в ра счете на одного
учащегося с ОПФР.
В специальных учреждениях образования должны быть созданы условия для проведения
коррекционных занятий (наличие кабинетов коррекционной работы, оснащенных необходимым
коррекционно-развивающим оборудованием, средствами обуч ения и учебной литературой).
В специальных учреждениях образования должны быть созданы условия для проведения
факультативных, стимулирующих и поддерживающих занятий, организационно -
воспитательной и кружковой работы, деятельности общественных организаций (о бъединений)
работников и учащихся.
В специальных общеобразовательных и вспомогательных школах -интернатах должны
быть созданы условия для круглосуточного пребывания учащихся.
В общеобразовательных учреждениях, создавших условия для получения образования
учащимися с ОПФР (далее – общеобразовательных учреждениях), обучение и воспитание
учащихся с ОПФР осуществляется в специальных классах или классах интегрированного
(совместного) обучения и воспитания.
Обучение и воспитание учащихся с ОПФР в общеобразовательном учреждении может
быть организовано при выполнении следующих общих требований:
укомплектованность педагогическими (дефектологическими) кадрами;
введение должности учителя-дефектолога в классах интегрированного (совместного)
обучения и воспитания полной наполняемости;
организация коррекционно-педагогических занятий (коррекционных занятий и уроков по
отдельным учебным предметам специального учебного плана) для учащихся с ОПФР в классах
интегрированного (совместного) обучения и воспитания неполной наполняемос ти;
материально-техническое и учебно-материальное обеспечение в соответствии с
государственными нормативами для специального учреждения образования;
наличие кабинета учителя-дефектолога, оснащенного необходимым коррекционно -
развивающим оборудованием, средс твами обучения и учебной литературой;
профессиональная и личностная готовность педагогических работников
общеобразовательного учреждения к обучению и воспитанию учащихся с ОПФР.
</p>

    </div>
{% endblock %}

school/templates/scholarship.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <h1 class="news_header">Стипендии и меры поддержки обучающихся</h1>
        <p>Обучающимся университета предоставляются следующие виды стипендий:</p>
        <ul>
            <li>государственная академическая стипендия</li>
            <li>государственная социальная стипендия</li>
            <li>стипендии Президента Российской Федерации и стипендии Правительства Российской Федерации;</li>
            <li>стипендии Президента Российской Федерации для студентов и аспирантов, обучающихся по направлениям подготовки (специальностям), соответствующим приоритетным направлениям модернизации и технологического развития российской экономики.</li>
        </ul>
        <p>Информация о мерах социальной поддержки обучающихся:</p>
        <p>В университете разработано Положение о порядке оказания материальной поддержки обучающихся.
Основными принципами материальной поддержки обучающихся являются: адресность, последовательность и соразмерность, информированность и открытость.
Материальная поддержка может быть оказана нуждающимся обучающимся университета, оказавшимся в жизненной ситуации, обстоятельства которой ухудшают их условия жизнедеятельности и последствия которых они не могут преодолеть самостоятельно</p>
        <div class="news_div"></div>
    </div>
{% endblock %}

school/templates/school.html
{% extends 'base.html' %}
{% load static %}


{% block main %}
    <div class="container">
        <img class="school_baner" src="{% static 'img/school.jpg' %}" alt="school">
        <nav class="header-menu">
            <ul class="header-menu-list">
                <li class="header-menu-item"><a class="school-menu-link" href="{% url 'school:departments' %}">Структура и органы управления</a></li>
                <li class="header-menu-item"><a class="school-menu-link" href="{% url 'school:requirements' %}">Образовательные стандарты и требования</a></li>
                <li class="header-menu-item"><a class="school-menu-link" href="{% url 'school:equipment' %}">Материально-техническое обеспечение</a></li>
                <li class="header-menu-item"><a class="school-menu-link" href="{% url 'school:scholarship' %}">Стипендии </a></li>
              
            </ul>
        </nav>
        <h1 class="news_header">Новости</h1>
        <div class="row">
            {% for new in news %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ new.img.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                {{ new.name }}
                            </h4>

                        </div>
                        <div class="card-footer text-center">
{#                            <button type="button" class="btn btn-outline-success">Подробнее</button>#}
                            <a class="btn btn-outline-success" href="{% url 'school:news_one' new.id %}">Подробнее</a>
                        </div>
                    </div>
                </div>
            {% endfor %}



        </div>
        <nav class="paginator" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not news.has_previous %} disabled {% endif %}">
                    <a class="page-link"
                       href="{% if news.has_previous %} {% url 'school:paginator' news.previous_page_number %} {% else %} # {% endif %}"
                       tabindex="-1" aria-disabled="true">Предыдущая</a>
                </li>
                {% for page in news.paginator.page_range %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'school:paginator' page %}">{{ page }}</a>
                    </li>
                {% endfor %}
                <li class="page-item {% if not news.has_next %} disabled {% endif %}">
                    <a class="page-link"
                       href="{% if news.has_next %} {% url 'school:paginator' news.next_page_number %} {% else %} # {% endif %}">
                        Следующая
                    </a>
                </li>
            </ul>
        </nav>
        <h2 class="news_header">Задать вопрос</h2>
        <form action="{% url 'index' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.question.id_for_label }}">Напиши вопрос</label>
{#                <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Your question">#}
                {{form.question}}
            </div>
            <div class="form-group">
              <label for="{{ form.email.id_for_label }}">Email адресс</label>
{#              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">#}
                {{form.email}}
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
    
    </div>

{% endblock %}

school/templates/teachers.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <h1 class="news_header">Учителя</h1>
        <div class="row">
            {% for teacher in teachers %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="#">
                        <img class="card-img-top"
                             src="{{ teacher.img.url }}"
                             alt="">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">
                            {{ teacher.name }}
                        </h4>
                        <p class="card-text">{{ teacher.description }}</p>

                    </div>
                    <!-- <div class="card-footer text-center">
                        <button type="button" class="btn btn-outline-success">Подробнее</button>
                    </div> -->
                </div>
            </div>
            {% endfor %}


        </div>
    </div>
{% endblock %}